
dls:
	pdflatex dm-dls-tech-design
##ps:
##	dvips -t a4 -o dm-dls-tech-design.ps dm-dls-tech-design
##	dvips -t letter -o dm-dls-tech-design.ps dm-dls-tech-design

##pdf:
##	dvipdf dm-dls-tech-design.dvi dm-dls-tech-design.pdf

##all: dvi ps pdf
lfc:
	pdflatex lfc-dls
